namespace rabcrClient {
    enum InventoryType :byte{
        Normal,
        Typing,
        BasicInv,
        Desk,
        FurnaceStone,
        FurnaceElectric,
        Macerator,
        Creative,
        Shelf,
        BoxWooden,
        BoxAdv,
        Mobile,
        Rocket,
        Charger,
        Miner,
        Radio,
        Composter,
        SewingMachine,
        OxygenMachine,
        Barrel,
        GameMenu,
    }
}